<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="FinalCart.aspx.cs" Inherits="Default3" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
    <asp:GridView ID="GridView1" runat="server" BackColor="White" BorderColor="#999999"
        BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Vertical" Style="z-index: 100;
        left: 376px; position: absolute; top: 244px" OnRowDataBound="GridView1_RowDataBound" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting">
        <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
        <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
        <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
        <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
        <AlternatingRowStyle BackColor="Gainsboro" />
    </asp:GridView>
    &nbsp;
    <asp:Button ID="Button1" runat="server" Height="68px" OnClick="Button1_Click" Style="z-index: 101;
        left: 780px; position: absolute; top: 344px; width: 190px;" 
        Text="Go to Payment Detail" UseSubmitBehavior="False" />
    <asp:Label ID="l1" runat="server" style="z-index: 103; left: 280px; position: absolute; top: 144px" Width="588px"></asp:Label>
</asp:Content>

